/* eslint-disable @typescript-eslint/no-unused-vars */
// 1. Heloo World task
// TODO: creaate excercise1 folder
// TODO: check node version
// TODO: check npm version
// TODO: check npx version
// TODO: init npm project
// TODO: install typescript
// TODO: generate tsconfig.json
// TODO: create src/index.ts with this code
function excercise1() {
  let greeting: string;
  greeting = 'Hello World';
  greeting += '!!!';
  console.log(greeting);
}

excercise1();
// TODO: run typescript in watch mode
// TODO: compare with javascript generated by typescript

// 2. loop which prints string to console n times
function excercise2() {
  // declare two varaibles - one of string, one of type number
  let str: string;
  let num: number;

  // assign string var value 'Hello'
  str = 'Hello';
  // assign number var value 3
  num = 3;

  // create a while loop which prints string variable to console 3 times
  let counter: number = 0;
  while (counter < num) {
    counter++;
    console.log(str);
  }

  // try to assign number variable to string variable - observe the error
  // str = num; // Type 'number' is not assignable to type 'string'.
}
excercise2();

// 3. code that generates array of numbers - from n to m
function excercise3() {
  // TODO: declare varaibles n and m of type number
  let n: number;
  let m: number;

  // TODO: declare varaible result of type array of numbers
  let result: number[] = [];

  // TODO: assign n and m some values - n = 1, m = 10
  n = 1;
  m = 10;

  // TODO: create a for loop which adds numbers from n to m to result array
  for (let i: number = n; i <= m; i++) {
    result.push(i);
  }

  // TODO: support case where m > n (reverse the order)
  // можливо я не так зрозумів завдання, але мені здається що тут має бути m < n, бо в нас в тз так і є що m > n (10 > 1) - тому в нас завжди буде змінений порядок
  // через це, я реалізував саме з такою логікою, що коли в нас n < m - виводиться від 1 до 10, а коли n > m - від 10 до 1
  if (m < n) {
    for (let i: number = n; i >= m; i--) {
      result.push(i);
    }
  }

  // TODO: support case where n > m (reverse the order)
  // TODO: print result array to console
  console.log(result);
}

excercise3();
// TODO: compile and run the code
