/* eslint-disable @typescript-eslint/no-unused-vars */
// 1. Heloo World task
// TODO: creaate excercise1 folder
// TODO: check node version
// TODO: check npm version
// TODO: check npx version
// TODO: init npm project
// TODO: install typescript
// TODO: generate tsconfig.json
// TODO: create src/index.ts with this code
function excercise1() {
  let greeting: string;
  greeting = 'Hello World';
  greeting += '!!!';
  console.log(greeting);
}
excercise1();
// TODO: run typescript in watch mode
// TODO: compare with javascript generated by typescript

// 2. loop which prints string to console n times
function excercise2() {
  // declare two varaibles - one of string, one of type number

  // assign string var value 'Hello'
  // assign number var value 3
  const name: string = 'Hello';
  const age: number = 3;

  // create a while loop which prints string variable to console 3 times
  let n: number = 0;
  while (n < age) {
    console.log(name);
    n++;
  }

  // try to assign number variable to string variable - observe the error
  // age = name; // error TS2322: Type 'string' is not assignable to type 'number'.
}
excercise2();

// 3. code that generates array of numbers - from n to m
function excercise3() {
  // TODO: declare varaibles n and m of type number
  // TODO: declare varaible result of type array of numbers
  const result: number[] = [];

  // TODO: assign n and m some values - n = 1, m = 10
  const n: number = 1;
  const m: number = 10;
  // const n: number = 10;
  // const m: number = 1;

  // TODO: create a for loop which adds numbers from n to m to result array
  if (m > n) {
    for (let i = n; i <= m; i++) {
      result.push(i);
    }
  }

  // TODO: support case where m < n (reverse the order)
  if (m < n) {
    for (let i = n; i >= m; i--) {
      result.push(i);
    }
  }

  // TODO: print result array to console
  console.log(result);
}
excercise3();
// TODO: compile and run the code
